# Generated by Django 5.2.13 on 2026-05-09 23:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_tipoarchivodocumento_archivodocumento_storage_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivodocumento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='fichaclinica',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='sexopaciente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipoarchivodocumento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'ordering': ['-fecha_aplicacion']},
        ),
        migrations.AlterField(
            model_name='archivodocumento',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia cardíaca en lpm (1 – 500)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia respiratoria en rpm (1 – 200)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg (0.01 – 999.99)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura corporal en °C (25.0 – 45.0)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(25.0), django.core.validators.MaxValueValidator(45.0)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha_aplicacion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='proxima_dosis',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
