# Generated by Django 5.2.13 on 2026-05-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_archivodocumento_options_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='sexopaciente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipoarchivodocumento',
            name='activo',
        ),
    ]
