# Generated by Django 5.2.13 on 2026-05-10 12:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_activo_from_catalogos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='activo',
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg (0.01 – 999.99)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('999.99'))]),
        ),
    ]
