# Generated by Django 5.2.13 on 2026-05-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_clinica_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivodocumento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='especie',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='sexopaciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='tipoarchivodocumento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinica'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sexopaciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoarchivodocumento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='especie',
            unique_together={('nombre', 'clinica')},
        ),
        migrations.AlterUniqueTogether(
            name='sexopaciente',
            unique_together={('nombre', 'clinica')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoarchivodocumento',
            unique_together={('nombre', 'clinica')},
        ),
    ]
