# Generated by Django 5.2.13 on 2026-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_clinica_not_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codigoverificacion',
            index=models.Index(fields=['email', 'usado'], name='idx_codigo_email_usado'),
        ),
    ]
