# Generated by Django 5.2.13 on 2026-05-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_add_index_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sexopaciente',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoarchivodocumento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
