# Generated by Django 5.2.13 on 2026-05-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_codigo_intentos_fallidos_catalogo_indices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='activo',
        ),
    ]
