# Generated by Django 5.2.13 on 2026-05-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_clinica_activo_otp_max_intentos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codigoverificacion',
            index=models.Index(fields=['email', 'creado_en'], name='idx_codigo_email_creado'),
        ),
    ]
