# Generated by Django 5.2.13 on 2026-05-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_archivodocumento_fecha_date_today_idx_codigo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='ficha_clinica',
            field=models.ForeignKey(blank=True, help_text='Ficha clínica desde la cual se originó este tratamiento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_asociados', to='clinic.fichaclinica'),
        ),
    ]
