# Generated by Django 5.2.13 on 2026-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_tratamiento_add_ficha_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
