# Generated by Django 5.2.13 on 2026-05-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_paciente_activo_tutor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='chip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
