# Generated by Django 5.2.13 on 2026-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_paciente_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='chip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
