# Generated by Django 5.2.13 on 2026-05-17 06:51

import uuid
from django.db import migrations

def gen_uuids(apps, schema_editor):
    modelos = [
        'Especie', 'SexoPaciente', 'TipoArchivoDocumento', 'Tutor',
        'Paciente', 'FichaClinica', 'Cita', 'Vacuna', 'Tratamiento', 'ArchivoDocumento'
    ]
    for nombre_modelo in modelos:
        MiModelo = apps.get_model('clinic', nombre_modelo)
        for fila in MiModelo.objects.all():
            fila.uuid = uuid.uuid4()
            fila.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_archivodocumento_uuid_cita_uuid_especie_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
