# Generated by Django 5.2.13 on 2026-05-17 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_alter_archivodocumento_uuid_alter_cita_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
