# Generated by Django 5.2.13 on 2026-05-17 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_add_clinica_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
